export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE',
    REGISTER_REQUEST : 'REGISTER_REQUEST',
    REGISTER_FAILURE : 'REGISTER_FAILURE',
    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
}

export const adminConstants = {
    REGISTER_REQUEST : 'REGISTER_REQUEST',
    REGISTER_FAILURE : 'REGISTER_FAILURE',
    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
}